cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"

brew "git"
brew "c2048"
brew "certbot"
brew "entr"  # Run command when file changes
brew "fzf"
brew "python3"
brew "grc"  # Log prettifier
brew "htop"
brew "hub"
brew "imagemagick"
brew "jid"
brew "jq"
brew "node"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "the_silver_searcher"
brew "tig"  # git on steroids
brew "tmux"
brew "tree"
brew "vim", args: ["with-python3"]
brew "wget"
brew "z"

cask "alfred"
cask "apptivate"
cask "iterm2"
cask "karabiner"
cask "karabiner-elements"
cask "keybase"
cask "lastpass"
cask "macdown"
cask "meld"
cask "shiftit"
cask "skype"
cask "spotify"
cask "vlc"
